### ISSUE TITLE
brand names/eponyms

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1012]
IMO brand names need to be part of the sentences we collect, what do you think?
At least in the german language there are many generic brandnames, that are used in favor of the actual name because they were so successful, and I'm fairly sure it's the same everywhere else (they are called Deonyme: https://de.wikipedia.org/wiki/Deonyme_nach_Sachgebiet , eponyms in english)
German examples:
- googlen
- twittern
- kärchern
- Tempo(-taschentuch)
- Tesafilm
- iPad (instead of tablet)
- Tipp-Ex
- Uhu
- Pritt
- Edding
- Stabilo
- Labello
- Aspirin
- Teflon
- Pampers
- Nivea
- Knirps
- Tupperdose
- Zewa
- Vileda

We probably cover some of them already, because their name is part of the actual language:
Tempo: speed or tissue
Uhu: eagle owl or glue

eponyms derived from people's names are not a problem, I guess, right?
- lindnern
- guttenbergen
(not the best examples because they are likely going to vanish soon, but I guess you know what I'm aiming for)
- Diesel

**Comment by jf99** [comment]
Imo, we need them. It's just the way people talk naturally. To complement your list:
- Oettinger-Englisch

**Comment by geroter** [comment]
Thanks for this @Djfe and @jf99 

This is very similar to this issue: #889 

In short, it's not particularly necessary to have brand names, place names, etc as part of the **audio corpus**, and therefore we don't need to worry too much about having it part of Common Voice. The reason is because of how the speech to text models are trained; there is a separate **text corpus** that can be applied later on.
