### ISSUE TITLE
"listen" can show you samples twice

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#1022]
I just noticed:
If common voice runs out of validatable samples, then it sends you samples, that you reviewed already before:
https://voice.allizom.org/de

I was able to realize that because of the number of samples on the staging server being too low.
I reviewed all of them with "no", so I'm not sure if that is part of the reason.

IMO, it should tell the user that it ran out of samples and congratulate him/her for achieving such a thing :)
and maybe recommend recording voice samples instead or something like that

Same goes for the recording tool, if it runs out of sentences for the user to record. (I haven't been able to check what currently happens then)

**Comment by Gregoor** [comment]
Heya, thanks for reporting that. Unfortunately we expect some duplication, due to our 3 servers using separate caches. So some servers don't know will not know which clips you've already validated, until they refill their cache. 
I think given this and some other problems we had with the cache (@a3nm mentioned one around getting the same sentences), we should throw out the cache and instead add "caching"-columns:
`clips(is_validated: boolean)`
`sentences(clips_count: number)`
That way we can query the DB on every request without costly queries (or these inconsistencies).

**Comment by Gregoor** [comment]
Done! (Should've done that before deploy 🙈 )
