### ISSUE TITLE
gzip & cache-headers for ftl files

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1093]
@gozer I just realized that I don't quite know how to do that. This should be the right file:
https://github.com/mozilla/voice-web/blob/master/nubis/puppet/web.pp

But there I can only add output filters by mime-types and I don't think fluent's FTL is a known mime type, is it?

**Comment by Djfe** [comment]
Can you also add Brotli pls?

**Comment by gozer** [comment]
I sure can do that, but can you be a bit more explicit in what you need in terms of file extensions and headers?

**Comment by Djfe** [comment]
@mikehenrty reduced traffic and latency
https://medium.com/oyotech/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4

essentially for free if you precompress all static files/if the server caches static files
(since it's mostly a config entry/no extra code is needed)

I'm not sure how much more it will improve page load times compared to gzip but I could take a look if you activate it on allizom as a test.

**Comment by Gregoor** [comment]
@gozer basically for all files with the `.ftl` extension. I did try adding a config for it to the apache web.pp file, but it had no effect.

**Comment by gozer** [comment]
This has been solved, however, I am going to suggest passing on Brotli at the time, as it requires a newer version of Apache than what we run, and I would suspect deflate/gzip already gets up pretty good compression ratios.

**Comment by Gregoor** [comment]
Thanks!
