### ISSUE TITLE
Number of validated hours dropped

### ISSUE THREAD

**Issue by jf99** [mozilla/voice-web#1098]
Yesterday, we had ~417 validated hours in English, now the progress bar is showing only 393 hours. What happened?

Also, will we get progress bars for other languages?

**Comment by Gregoor** [comment]
Sorry, that's my bad. Here's what happened: When we rolled out the multi-lang contribution, I forgot to adjust the progress bar to only track english clips. I made that changed yesterday, which is why now there are ~40 hours less displayed (which are from clips in other languages).
RE bars for other languages, let's move that over to #1099 as it has a more fitting title for that
