### ISSUE TITLE
add shortcut for re-recording/going back to last sentence

### ISSUE THREAD

**Issue by s-light** [mozilla/voice-web#1207]
every now and then i mess up my first time recording - so it would be really cool to have an additional shortcut to get back to the last sentence for re-recording.

also if you have finished recording all 5 a shortcut to start a auto-play to check if all 5 are fine would be great!

**Comment by mikehenrty** [comment]
cc @m-branson

**Comment by Gregoor** [comment]
> @Gregoor how about using the back arrow for this?

Arrow-Left? Sure! Maybe we should move this discussion over to #1052 so that it's consistent. I think I'm starting to like the idea more of utilizing the cursor keys (especially [your proposal](https://github.com/mozilla/voice-web/issues/1052#issuecomment-401874211)). And and undo key also seems very valuable to have.

> @Gregoor could A work for this? could see it utilized during a session regardless of what segment you're recording. Pressing A would autoplay any recording you've done.

Sure, though we might want to have it definable per language. Or not. (Currently all the shortcuts related to words are). Would we also surface it in the UI in some way?
