### ISSUE TITLE
add language

### ISSUE THREAD

**Issue by eduaddad** [mozilla/voice-web#1277]
add the Brazilian Portuguese language to be able to contribute

**Comment by ftyers** [comment]
Should we just add Portuguese ? ... We don't separate types of English, German or French. Sure people speak differently in Portugal and Brazil, but they do in all of those languages too.

**Comment by ftyers** [comment]
@reuben European Portuguese speakers really have trouble understanding you when you are speaking Portuguese ? That's quite surprising. Also, where would people from Angola or East Timor contribute ? ... What you say about "unpolished" also applies to English/French/German.

**Comment by reuben** [comment]
I can't speak for hundreds of millions of speakers, of course, but my experience as well as that of people I've talked to about this is that it's like when you're speaking in one language and someone comes up to you speaking a different language. It can take a second or two for your brain to context switch and frequently you don't understand the first sentence or two. After that it gets easier but definitely not to the same level of two Brazilian Portuguese speakers.

About other Portuguese languages, I think those too should be collected separately. One can leverage the existing Portuguese localizations for bootstrapping the process and then adjust to each language.

One can always merge two datasets that are appropriately labeled if they want to have all Portuguese languages in a single dataset.

Note that this doesn't necessarily have to be an entirely different Common Voice UI localization or even a different archive file when releasing the dataset. My only request is that each audio file is tagged with the appropriate variant of Portuguese so that automatic manipulation of the data is possible.

**Comment by eduaddad** [comment]
The meaning of words of Brazilian Portuguese and European Portuguese are different and will be difficult to understand.

**Comment by ftyers** [comment]
@eduaddad vc tem uma lista daqueles palavras? eu acho que não tem muitas, e não tem mais que p.ex. entre inglês de Inglaterra e inglês dos Estados Unidos ... pensa em palavras como "chips" e "pants" por exemplo. Mais tudo bem... pra mim não é muito importante, só que acho que é muito curiosa a mentalidade ... pra alguém de fora parece que o português é uma lengua com dois principais acentos muito diferentes... igual como as outras lenguas grandes do mundo.

@reuben agree wrt. tagging, it should be the same for all language variants. But again, I really don't see any of the problems you raise as being qualitatively or quantitatively different from the other languages I mentioned. If you are worried about European Portuguese being swamped, think about Irish or Scottish English compared to English English, or English English compared to American English. Let alone Quebecois French compared to Metropolitan French. And if it's a localisation question, then sure I'd love to have the Common Voice interface in my variant of English --- would you support that too? --- but I'm not sure that it's worth the fractioning.

**Comment by reuben** [comment]
If individual audio samples have the variant associated with them, I'm happy. The UI localization would be good to have, I don't understand how it fractions anything?

**Comment by mikehenrty** [comment]
The question here becomes: how do we allow users to report the difference between Portuguese variants. Two different ways exists:

1. Allowing users to select it in the language dropdown (ie. where to localize the site, `pt` vs `pt-BR`).
2. Allowing users to select it in their profile

The advantage to 1 above is that all users will be forced to make that choice, and so we will always have this data segmented. But then we will need to maintain separate text corpora for each langauge. Is this the right thing to do for Portuguese (for Spanish we decided to merge them so they can share the text corpus).

The advantage to 2 is that is allows us to share website localization and the text corpus. But it doesn't force users to choose this (indeed only 20% - 25% of users fill out their profile).

By the way, in relation to the original reason this bug was filed (which I'm not sure why it's closed now), in order to add Brazilian Portuguese, we need a lot of public domain sentences for people to read. Does anyone know where we can find such sentences?

**Comment by belkacem77** [comment]
I ignore the gap between European Portugeese, Brazillian.. or others. I'm Algerian, and as an example when I listen to French (I'm contributing) spoke by French, Canadians, Belgians, Swiss, Africans, North Africans... I feel some differences in pronounciation, but when writing, the rules are the same. Same thing when listnening to American or British English, there is no large gaps. It's my point of view, on such corpora, I don't think we need to create a copus for each English, French, Spanish, Potugeese, Arabic, and even Kabyle, my language with 4 major variants.
For Kabyle, we are recoding all variants with the same corpus and it's something rather good. I'd like to take part within the Portugeese team but sorry, I don't speak it, and would like to do.  :)

I love languages and people(s), thanks to Common Voice teams
