### ISSUE TITLE
Clips Stats

### ISSUE THREAD

**Issue by grailean** [mozilla/voice-web#1392]
- The style of the dropdown needs to be like this: https://www.dropbox.com/s/z8ogb4g56noxhtw/3d403464.png?raw=1

- Missing the hover pop up for additional data: https://www.dropbox.com/s/rn1mr5k4pn11tm5/855tjxq7.png?raw=1

- Small issues https://www.dropbox.com/s/609ne69yx4m95mx/vb3l2rtd.png?raw=1

**Comment by Gregoor** [comment]
@mbransn: From the designs it looks like a plot with a skewed time-axis is wanted? I'd personally find that rather confusing. Just want to make sure that's what we want, before I changed the implementation.

**Comment by mbransn** [comment]
@Gregoor re: dropdown, if you can make hover and active states happen we'd really really appreciate it. 😬 

For the 0 spacing call out, I think it looks good as is line-height wise. The width is an issue though, now that we've dropped 'total hours' is it possible to allow these two stat categories to take up the width originally design for three categories?

For the timeline, the date stamp should be `6mo  4mo  2mo  1mo  1week` rather than the full `1/1/2018` date you are utilizing. Make sense?

In @grailean's screenshot from the Zeplin UI, we're also missing the hover state that gives the actual detailed numbers. @Gregoor if you don't feel something will make it to production on our current timeline, please make a separate issue, label as an `enhancement` `p1` and tag me in it, so it doesn't get lost in the backlog. 👍

**Comment by Gregoor** [comment]
> @Gregoor re: dropdown, if you can make hover and active states happen we'd really really appreciate it. 😬

I'll get an active style in. Though not sure if I'll get done with hover this week, as that will require a custom dropdown reimplementation. I hope in the future we can either refrain from custom implementations or just reuse this dropdown component everywhere.

> For the timeline, the date stamp should be 6mo 4mo 2mo 1mo 1week rather than the full 1/1/2018 date you are utilizing. Make sense?

@mbransn the labeling makes sense to me, but I'm still unsure if you literally want the ticks to be `6mo 4mo 2mo 1mo 1week`? Sorry if I'm hammering that point, but I don't think it's a good idea to skew a plot's time-scale like this, so I want to make sure it's at least what y'all want to go with.

> In addition, for the left-side time measurements it would be brilliant to round up or down to the nearest 10m or 1h. The data plot should visually fall within a rounded segment still, but the hover UI (see below) will provide detail if it is desired.

Agreed and captured in #1404.


I'm positive on the rest and working on it. Thanks for the feedback 👍

**Comment by mbransn** [comment]
@Gregoor sounds like we got to a good point on this during our call today: UX desire is for users to have a view of a skewed timeline. If this is best achieved via a dropdown, great. If it is best achieved via a different model, please recommend it. :) Let us know where you get with this when ready. 👍

**Comment by Gregoor** [comment]
It's all skewed now 🙃
