### ISSUE TITLE
AudioParam Error when Listening on Staging

### ISSUE THREAD

**Issue by Gregoor** [mozilla/voice-web#1456]
Error is: `Failed to set the 'value' property on 'AudioParam'`

@est31 should we maybe put the gain clamping that you commented out in?

**Comment by est31** [comment]
Most likely the error is accompanied with something like "The provided float value is non-finite".

I guess the issue is with audio files that are *really* silent. If you look at this code:

https://github.com/mozilla/voice-web/blob/fcd72e6af6c122ffde5930f775b6680ffb54d85a/web/src/components/normalized-player.tsx#L44-L52

you can see that if up to the 95th percentile, there are zeros in the array, then `a` becomes zero as well, and gain becomes infinity.

As for which values to clamp on.

I've listened to 100 english samples and these were the gain values I could record for the gain node (via the web audio panel in the developer tools):
 
<details>

  <summary>Full list (click to expand)</summary>

```
1.4141058921813965
0.3119737207889557
0.5177436470985413
0.8261668682098389
0.5841774344444275
0.9099913835525513
1.7025984525680542
0.9391054511070251
0.31226101517677307
0.910223126411438
0.7119715213775635
2.30153751373291
0.35450655221939087
0.6654325127601624
1.0860929489135742
0.5578415393829346
3.7291812896728516
1.190458059310913
1.3212358951568604
0.718613862991333
0.44371408224105835
0.8825674057006836
1.7018094062805176
0.9468435049057007
0.4479397237300873
1.735522985458374
1.9814941883087158
1.5603681802749634
2.9901607036590576
2.017237663269043
3.508399248123169
4.680166721343994
1.0049750804901123
0.9296541810035706
1.011601209640503
1.6702468395233154
0.7445489168167114
0.44437554478645325
0.5531359314918518
2.5242550373077393
0.48421990871429443
1.100569248199463
2.7738332748413086
0.8087984323501587
1.6058409214019775
2.08791446685791
1.0819802284240723
0.9873701333999634
0.6645107269287109
0.5765944719314575
1.8275189399719238
1.0913845300674438
1.5331097841262817
0.5040572285652161
0.8563435077667236
1.2477151155471802
0.8150331377983093
0.612337589263916
1.0342739820480347
0.4919246435165405
0.4489839971065521
1.2170652151107788
1.2711321115493774
0.5882748961448669
0.9784404635429382
4.99714994430542
0.6841352581977844
1.0152524709701538
0.4433082044124603
0.8477708697319031
1.2355821132659912
2.756833791732788
0.6790756583213806
0.47169244289398193
0.4931299388408661
2.8073456287384033
5.3706560134887695
1.073489785194397
1.4679698944091797
0.7594287991523743
2.4848592281341553
1.4621777534484863
2.213236093521118
1.0224040746688843
1.4003641605377197
1.301023244857788
1.2380614280700684
1.376427412033081
1.2125866413116455
2.1996705532073975
0.6056973338127136
0.2886342406272888
1.532380223274231
0.800443172454834
1.0940206050872803
1.0776997804641724
1.4551836252212524
1.4580248594284058
0.45387032628059387
2.269191265106201
```

</details>

The maximum gain value was 5.37 and the minimum one was 0.289.

The commented out clamping code uses 0.02 and 100:

https://github.com/mozilla/voice-web/blob/fcd72e6af6c122ffde5930f775b6680ffb54d85a/web/src/components/normalized-player.tsx#L54-L56

Given that the random sample of 100 samples is not even close to those limits (factor of 10 for the minimum, and factor of 20 for the maximum), I think those limits are okay.

I mostly commented out the code because I wasn't sure it was needed at all, and thought it could be commented back in once there is a reason to put them in again. This seems to be the case now so :+1: to enabling clamping.

**Comment by Gregoor** [comment]
Awesome, thank you very much for that those details@est31! it very much helped me to get an idea of what's actually going on.
