### ISSUE TITLE
Remove autologin toggle from edit email window

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1620]
Autologin toggle should be removed from the login window when doing email editing, as it is disabled by default. 
![autologin toggle](https://user-images.githubusercontent.com/5293100/49086106-69c17800-f25c-11e8-96e5-3e35e686429f.png)

**Comment by Gregoor** [comment]
@hidde is there a parameter for that? 🙃

**Comment by hidde** [comment]
There's no parameter for this, I'm afraid, @Gregoor.

Easy to add though, do you need it soon?

**Comment by hmitsch** [comment]
For transparency: @hidde @akatsoulas and @hmitsch want to discuss the benefits and disadvantages of using _Account Verification NLX_ instead of adding additional parameters to _regular NLX_.

This would also allow us to change the text from `Log In or Sign Up with email` to `Log In with email`.


PS: Thanks to @hidde for keeping this on your radar!

**Comment by hidde** [comment]
Hey @Gregoor! Please use `account_verification=true`.

Not only will it get rid of the autologin toggle, it will also prevent login methods being set as a user's new autologin method while they're confirming their email address.

**Comment by Gregoor** [comment]
Done, thanks for adding that switch!
