### ISSUE TITLE
Other markup for "(You)"

### ISSUE THREAD

**Issue by RobinvanderVliet** [mozilla/voice-web#1658]
Maybe the word "(You)" should have another color or have a different mark-up. Somebody has called themself "(Vi)" (Esperanto for "(You)"), which confused me during multiple days. I thought it was a bug...

![confusing-name](https://user-images.githubusercontent.com/692029/49345213-f7003480-f681-11e8-86ff-7d7cc45fdab0.png)

**Comment by Gregoor** [comment]
Good point. @mbransn wdyt?

**Comment by mbransn** [comment]
>Somebody has called themself "(Vi)" (Esperanto for "(You)"), which confused me during multiple days.

Well that is indeed an unexpected edge case. Thanks for calling out @RobinvanderVliet. 

@Gregoor are we indeed sure the person identifying as `(Vi)` did this intentionally and it isn't an odd bug of sorts? Intentional = their name is some variation of Vi or they are looking to be comical/playful. I can assume confusion wasn't their intent, though we may want to attempt to rectify rather than change the mark-up as that could easily be mimicked again? And for the color change, it is already blue for this reason, to set `you` apart for easier visibility.

cc @LRSaunders for visibility
