### ISSUE TITLE
No link to sentence collector anywhere

### ISSUE THREAD

**Issue by gtimoshaz** [mozilla/voice-web#1858]
The only place where I found a link to SentenceCollector is here, on Github, in issues. Maybe there should be some links on voice.mozilla.org? Even if you click "take part" button on a "in progress" language, you see "subscribe", but you don't see link to sentence collector!
I think it should be improved.

**Comment by TonnesM** [comment]
Shouldn't this change be visible to translators?

**Comment by TonnesM** [comment]
cc @Gregoor

**Comment by Gregoor** [comment]
oh, good flag, thanks! I didn't change the string, because I only appended something to it. I guess there's no Pontoon way to notify translators? So I'll have to add a new string for that?

And since I forgot to comment before: The commit that closed this issue added a sentence collector link to the FAQ.

**Comment by TonnesM** [comment]
I’m not exactly sure, but think you need to use a new string ID in order for it to be picked up. Cc @flodolo ?
