### ISSUE TITLE
Provide detailed recording and validation guidelines

### ISSUE THREAD

**Issue by dabinat** [mozilla/voice-web#1872]
I feel that the site would benefit from detailed official guidelines on how to record and validate.

For instance, I have heard some recorders repeat the sentence twice, others speak the punctuation out loud and some correct incorrect grammar in the sentence. There isn’t anything on the site that tells them not to do that.

For validation, there are some clips that fall into grey areas and detailed guidance here would be helpful. For instance, background noise is supposed to be ok, but where does the line fall? What background noise would be considered a fail? I generally allow other voices if they are reasonably quiet and overpowered by the main voice, but that’s just a rule I made up. Is that the correct thing to do? I have no idea. That’s why proper rules are needed.

I’m happy to submit a PR with guidelines I feel are reasonable if someone tells me where it would be appropriate to put it. It could go in the FAQ but it might get lost there. I think it’s better to have its own page, perhaps linked from the section that appears when you hover over the Speak/Listen buttons and it shows today’s progress.

**Comment by MichaelNMaggs** [comment]
I agree. At present there are quite a large proportion of recordings that fall into the grey area where it's unclear whether to answer yes or no. I've prepared a draft set of guidelines, with examples, and for want of a better place to put them I'll post them here.  Perhaps we could use this thread to discuss and finalise something?

**Comment by MichaelNMaggs** [comment]
**DRAFT GUIDELINES FOR REVIEWING RECORDINGS**

**Problems with the written text**

Ignore minor problems of punctuation if they don't affect the recording, but reject punctuation errors that may prevent a machine learning algorithm from properly recognising words:

* :white_check_mark: [Written text says:] *“the giant dinosaurs of the Triassic,*   
[The punctuation errors don't affect the recording]
* :x: [Written text says:] *The giant dino”saurs of the Triassic.*  
[This may make it difficult to recognise ‘dinosaurs’ as a word]

Reject if the text includes obvious typos or accidental spelling or grammatical errors, but accept texts with slang terms and apparently intentional spelling variations. Before rejecting for spelling errors, remember that alternative spellings might be normal elsewhere in the world:

* :x: [Written text says:] *The giant dinesaurs of the Triassic.* 
[Obvious spelling error]
* :x: [Written text says:] *The giant dinosaurs if the Triassic.* 
[Obvious typo for ‘of’. Reject whether the reader has read ‘if’ or ‘of’]
* :x: [Written text says:] *Is that to many potatoes for you?*  
[Obvious typo for ’too’. Reject even if read ‘correctly’]

* :white_check_mark: [Written text says:] *April is the cruellest month.*  
[British English]
* :white_check_mark: [Written text says:] *April is the cruelest month.*   
[US English]

* :white_check_mark: [Written text says:] *Are ya gonna hit ‘em?*    
[Slang and unconventional terms are OK]
* :white_check_mark: [Written text says:] *It was the womans bag.*   
[Should be “woman’s”, but ignore as it doesn’t affect the recording]

**Problems with the recording**

**Misreadings**

You need to check very carefully that what has been recorded is *exactly* what has been written - reject if there are even minor errors. Common mistakes include:

* missing out ‘A’ or ‘The’ at the beginning of the recording
* missing an ’s’ at the end of a word
* Reading contractions that aren’t actually there, such as “We’re” instead of “We are”
* Missing the end of the last word by cutting off the recording too quickly.
* Taking several attempts to read a word.

For example:

* :white_check_mark: The giant dinosaurs of the Triassic.
* :x: Giant dinosaurs of the Triassic. 
[‘The’ omitted]
* :x: The giant dinosaur of the Triassic. 
[Should be ‘dinosaurs’]
* :x: The giant dinosaurs of the Triassi-.  
[Recording cut off before the end of the last word]
* :x: The giant dinosaurs of the Triassic. Yes.  
[More has been recorded than the required text]
* :x: The giant dinosaurs of the Tri- Triassic.  
[The first ’Tri-‘ is not in the written text]

* :white_check_mark: We are going out to get coffee.
* :x: We're going out out to get coffee.  
[Should be “We are”]
* :x: We are going out to get a coffee. 
[No ‘a’ in the original text]

**Varying pronunciations**

Be cautious before rejecting a clip on the ground that the reader has mispronounced a word, or has put the stress in the wrong place. There are a wide variety of pronunciations in use around the world, some of which you may not have heard in your local community. If the reader has evidently never come across the word before, and is making a wild and incorrect guess at the pronunciation, you can reject. Otherwise, please provide a wide margin of appreciation for those who may speak differently from you. If you are unsure, please use the skip button.

**Background noise**

We want the machine learning algorithms to able to handle a variety of background noise, and even relatively loud noises can be accepted provided that they don’t prevent you from hearing the entirety of the text. Quiet background music is OK; music loud enough to prevent you from hearing each and every word is not.

* :white_check_mark: {Sneeze} The giant dinosaurs of the {cough} Triassic.

* :x: The giant dino {cough} the Triassic. 
[Part of the text can’t be heard]

If the recording breaks up, or has crackles, reject unless the entirety of the text can still be heard:

* :x: {Crackle} giant dinosaurs of {crackle} -riassic. 
[Part of the text can’t be heard]

**Background voices**

A quiet background hubbub is OK, but we don't want additional voices that may cause a machine algorithm to identify words that are not in the written text. If you can hear distinct words apart from those of the text, the clip should be rejected. Typically this happens where the TV has been left on, or where there is a conversation going on nearby.

* :x: The giant dinosaurs of the Triassic. [read by one voice]  Are you coming? [called by another]

**Volume**

There will be natural variations in volume between readers. Reject only if the volume is so high that the recording breaks up, or (more commonly) if it is so low that you can't hear what is being said without reference to the written text.

**Reader effects**

We want to collect recordings of people talking in their natural voice. Please reject recordings that are deliberately unnatural, for example those that are shouted, sung, whispered, or obviously delivered in a ‘funny’ voice.

**Comment by jmontane** [comment]
Adding a help button pointing to recording and reviewing guidelines would be a good feature

**Comment by MichaelKohler** [comment]
Given that there is that Discourse topic, I'm closing this issue.
