### ISSUE TITLE
Editing the goal doesn't keep existing progress

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1906]
[Preconditions]:
-set goals (weekly or daily for both Listen and Speak)
-progress in goal achievement

[STR]:
1.Go to https://voice.allizom.org/en/goals
2.Go to Custom goals section and click the edit button
3.Edit the goal

[Expected result]:
The goal should be updated, the progress should be kept

[Actual result]:
The goal is updated, the progress is marked as 0%

**Comment by Gregoor** [comment]
That's by design. Though I did want to put a modal in that informs user that setting a new goal overwrites the existing one.

**Comment by Gregoor** [comment]
We have a warning modal now :)

**Comment by mbransn** [comment]
@Gregoor I'll just reopen this issue based on today's quick mtg if that's alright? 

Expected outcomes that we're currently missing:
- Existing selections should be pre-filled for each step (currently step 2 and 3 are buggy)
- Top of card progress bar starts at step 1 when entering
- Progress bar follows even if someone skips ahead; e.g. I select 3 and both 1 & 2 reflect as done because they're prefilled with prior selections

I will review copy for the abort modal and tag you in the content outline with updates :)

cc @rleitan
