### ISSUE TITLE
Add Basque to the dataset page

### ISSUE THREAD

**Issue by Txopi** [mozilla/voice-web#1911]
In 7 days we are going to give a press conference to start officially the Common Voice recordings in Basque language. Is it possible to make Basque recordings downloadable like other languages? For example, Irish has less hours than Basque and its dataset is downloadable. Thank you very much!

**Comment by nukeador** [comment]
Hi @Txopi 

We should probably move this to discourse, since it's a question about the dataset.

Quick answer: Dataset releases are really time consuming for the team and we are still trying to figure out how to be able to release them more often, but unfortunately I don't have an answer yet, I'll flag this with the team but checking our current workload there is not much we can do in the coming 7 days.

I'm so sorry for that and I hope you understand.

Cheers.
