### ISSUE TITLE
[mobile] FAQ questions are visible underneath the sticky menu

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#1993]
**Env:**
iPhone x and 7, iOS 12.2, Firefox and Safari

**STR:**
Navigate to https://voice.allizom.org/en/faq-new
Scroll down on the page

**Expected:**
Questions are not visible underneath the sticky menu, while scrolling the page

**Actual:**
Questions are visible underneath the sticky menu. See [video](https://vimeo.com/333699443)

**Comment by arnavvats** [comment]
Hi, would like to take up this issue.

**Comment by arnavvats** [comment]
Hi, fixed the issue and created a pull request . Please review.

**Comment by munteanu210** [comment]
@viorelaioia Thanks for reviewing this and for identifying this problem. 

@arnavvats Thanks for fixing this! However, please note that your fix eliminated the menu transparency on mobile. Apparently it works. However, when the menu is not sticky yet, the background is a bit different from the one underneath, so as the one underneath has a gradient. [See video](https://drive.google.com/open?id=1fNPCR5vvUR2lgc70kKTWF5xEYXNBhNfp). It's hard to detect it, but I noticed it right away, because I know how it was initially. Can you fix it, or should I find a way to fix it? Please let me know. Thanks!

**Comment by arnavvats** [comment]
the background transparency has to be eliminated for the fix, and i used the same color code for the menu background, maybe a linear gradient could look better ?

**Comment by munteanu210** [comment]
@viorelaioia, I fixed this problem.

**Comment by viorelaioia** [comment]
Verified as fixed
