### ISSUE TITLE
Search button is not correctly displayed

### ISSUE THREAD

**Issue by rleitan** [mozilla/voice-web#1994]
Environment:
Windows 10, Mac OS 10.14 - Firefox, Chrome
[STR]:
1.Open https://voice.allizom.org/en/faq-new

[Expected result]:
"Search for answers" placeholder should be black 
Search button should be visible

https://app.zeplin.io/project/5a9eec5c53a9a2685450d4be/screen/5c92b7a7e6cbce24f53dfe6e

[Actual result]:

![2019-05-02_12h13_57](https://user-images.githubusercontent.com/41474886/57066457-e60d2b00-6cd4-11e9-8224-3dc3913dc2ab.png)

**Comment by rleitan** [comment]
@munteanu210

**Comment by arnavvats** [comment]
Hi, would like to take up the issue.

**Comment by arnavvats** [comment]
We can disable the auto search or keep this the current way. But how do we improve the UX?
@Gregoor can you give any suggestions?

**Comment by munteanu210** [comment]
@arnavvats the search functionality was thoroughly discussed and there is a set way we want it to work. We don't want the auto search disabled, because it was done on purpose after discussing it with the team. Also, a decent amount of work went into the auto search to make it work fast and pull results in the way it currently does. I will fix the search icon so that it is displayed correctly on all browsers. As for allowing users to click on the search icon - that is doable. (Here is what I mean by Search button: [https://www.screencast.com/t/8P9db3r7d4sS](https://www.screencast.com/t/8P9db3r7d4sS)) However, we can also keep the Search button there for display and aesthetics purposes. As long as the auto search works well (and it does), users will use the auto search and will not need to press on the Search button.

**Comment by arnavvats** [comment]
okay, nice.
