### ISSUE TITLE
About Page UI issues

### ISSUE THREAD

**Issue by georai** [mozilla/voice-web#2012]
@munteanu210 For the sticky menu: 
1. For the sticky menu: please move the menu with some pixels up to not have the gap at all between the tabs. 
2. Get involved section: issues with the spacing and Discourse icon is missing.
3. Become a partner to be clickable with the same pop up  like Contact Us button. @mbransn right?

Mobile version:
1.Reduce Mars illustration with 25%.
2. Icons issue.
3.Remove the tab color. 
4. Make the tabs waves with no shadow and 15% smaller.

**Comment by munteanu210** [comment]
@georai thanks for reviewing these pages and for you feedback. I am working on making these edits.

**Comment by munteanu210** [comment]
@georai, I implemented some of your feedback already. I'm still working on it and will submit the rest of the updates shortly.

**Comment by munteanu210** [comment]
@georai I did all the updates that you requested. The only update I did not do is making the tabs waves with no shadow on mobile. [Here is](https://www.screencast.com/t/1vn2fqJju) how the tab shadows show on mobile. As you can see, the shadow give shape to the tabs and make the tabs visible. Without the shadow, the tabs aren't visible because the tabs are white and the background is white. [See screenshot](https://www.screencast.com/t/wVEaSWNZ). 

Let me know if you agree with keeping the tabs shadow on mobile, or if you still want me to remove the shadow.
