### ISSUE TITLE
Request to add `Karakalpak` language to the list

### ISSUE THREAD

**Issue by beknazar** [mozilla/voice-web#2236]
I wanted to start contributing with our local students to [Karakalpak](https://en.wikipedia.org/wiki/Karakalpak_language) corpus.

Thanks in advance!

**Comment by ftyers** [comment]
Hi @beknazar ! You will need to use the [sentence collector](https://common-voice.github.io/sentence-collector/#/) to contribute sentences. Karakalpak is not there at the moment, but @MichaelKohler can add it. The language code is `kaa`. 

@beknazar two more questions:

* Do you have the corpus online somewhere? 
* Have you enabled Karakaplak in [Pontoon](https://pontoon.mozilla.org/)?

**Comment by MichaelKohler** [comment]
> Karakalpak is not there at the moment, but @MichaelKohler can add it. The language code is kaa.

Sure, I could do that. Is "Karakaplak" the English name or also the native name? We show both the English name and the native name in the Sentence Collector dropdown.

**Comment by ftyers** [comment]
@MichaelKohler sent a PR, #296.

I also contacted Peiying to get Karakalpak enabled in Pontoon.

**Comment by beknazar** [comment]
> Hi @beknazar ! You will need to use the [sentence collector](https://common-voice.github.io/sentence-collector/#/) to contribute sentences. Karakalpak is not there at the moment, but @MichaelKohler can add it. The language code is `kaa`.
> 
> @beknazar two more questions:
> 
> * Do you have the corpus online somewhere?
> * Have you enabled Karakaplak in [Pontoon](https://pontoon.mozilla.org/)?

Hey Francis,

- Can we start it with the articles in KAA Wikipedia?
- I don't see KAA in the languages list for the common voice project. How does one add a new language over there?

**Comment by beknazar** [comment]
> > Karakalpak is not there at the moment, but @MichaelKohler can add it. The language code is kaa.
> 
> Sure, I could do that. Is "Karakaplak" the English name or also the native name? We show both the English name and the native name in the Sentence Collector dropdown.

- English: Karakalpak
- Native: Qaraqalpaq

**Comment by ftyers** [comment]
> Hey Francis,
> 
>     * Can we start it with the articles in KAA Wikipedia?

@nukeador can you answer this from the legal point of view?

From the linguistic point of view, Wikipedia articles are ok, but you would be better to start with sentences more like your target use case. For example if you are interested in creating a voice assistant then try to include questions and commands rather than just descriptive/declarative sentences. 

I understand part of the issue will be orthographic as Karakalpak has gone through a number of orthography revisions over the last few years and it looks like some articles in Wikipedia are still written in the old orthography. @jonorthwash do we have a Karakalpak orthographic convertor?

>     * I don't see KAA in the languages list for the common voice project. How does one add a new language over there?

First you need to enable the site in Pontoon, when it is enabled and partially localised it should be automatically added to the [Common Voice staging server](https://voice.allizom.org/). When there are enough sentences it should get added to the main Common Voice site.

**Comment by MichaelKohler** [comment]
> Can we start it with the articles in KAA Wikipedia?

As far as I know there are no legal limitations of what languages can be extracted, as long as it's just 3 sentences per article (which the Scraping tool does). Nuke can confirm if needed.

For the scraping, you will first need to create a rules file for `kaa`. You can then test the extraction according to the README in https://github.com/Common-Voice/common-voice-wiki-scraper.  Once you're happy with the result, we will need others (preferably linguists) to verify and calculate the error rate through a few sample files that got extracted in your test. You can also find quite a few answers to questions here: https://discourse.mozilla.org/t/technical-feedback-needed-wikipedia-extractor-script-beta/42983 . Happy to help if you need any technical help!

**Comment by jonorthwash** [comment]
> @jonorthwash do we have a Karakalpak orthographic convertor?

Yes, but it might not do what you want, and it might not be very good if it does.  But it wouldn't be hard to make a good one that does what you're after, and it's been on my list of things to do anyway.  If you remind me, I'll look into it in a couple days.  (Sálem, @beknazar!)

**Comment by nukeador** [comment]
Hi,

This is the process for new languages:

https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530

Wikipedia process is explained here:

https://discourse.mozilla.org/t/technical-feedback-needed-wikipedia-extractor-script-beta/42983

Since this is a conversation, not a technical change, let's move it to discourse (we don't have bandwidth to monitor both channels for discussions, sorry)

https://discourse.mozilla.org/c/voice

**Comment by ftyers** [comment]
@beknazar Pontoon has been enabled for Karakalpak. https://pontoon.mozilla.org/kaa/common-voice/  If you'd like more help, please join us on Matrix or Discourse.
