### ISSUE TITLE
The Top Team leaderboard does not take into account of team member points

### ISSUE THREAD

**Issue by can-007** [mozilla/voice-web#2336]
I contributed and earned some bonus, but the points did not reflect on the Top Team leaderboard.

**Comment by phirework** [comment]
Even after 20 minutes?

**Comment by can-007** [comment]
No, not even after 20 minutes. The Top Team only calculated the teams’ bonuses based on the time these bonus were earned, which may not be appropriate, because the team bonus earnings will be a manual operation carried after the week.

**Comment by can-007** [comment]
https://github.com/mozilla/voice-web/pull/2335 was meant to fix this in a quick but uneasy way.

**Comment by mbransn** [comment]
+1, confirmed this is still an issue and related to my comments in #2337

**Comment by mbransn** [comment]
I've realized now that I was confusing Top Team leaderboard with Team leaderboard. @can-007 the Top Team leaderboard will only reflect points awarded based on team challenge outcome each week. These will be assigned manually by Riley at the end of each week and are based on the 100, 80, 60 point model for 1st, 2nd and 3rd place each week.

<img width="597" alt="Screen Shot 2019-11-19 at 3 42 09 PM" src="https://user-images.githubusercontent.com/18686986/69196377-2f8f5d00-0ae3-11ea-8b1d-5318cc77ff65.png">

Closing as it is expected behavior for this leaderboard to not count team member points.
