### ISSUE TITLE
User is displayed 2 times in the leaderboard when navigating to Challenge page first time after login

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/voice-web#2339]
**STR:**

1. Login to CV with an account signed up to IBM team
2. Navigate to Challenges page
3. Checkout the "IBM Team Progress"

**Expected:**
Users are displayed only once in the dashboard

**Actual:**
User "mikesonf" is displayed 2 times in teh dashboard. If I refresh the page, the user is displayed only once, as expected 

2 different accounts, part of the IBM team, first login
![image](https://user-images.githubusercontent.com/5293100/68950188-50467280-07c4-11ea-8e12-5d1de36832b3.png)
![Screenshot_2019-11-15 Common Voice by Mozilla](https://user-images.githubusercontent.com/5293100/68950448-dbc00380-07c4-11ea-8a26-101565195a7c.png)

**Comment by rileyjshaw** [comment]
I just tried, and couldn't reproduce this issue.  I think it was fixed by some work we did on deduplicating accounts, and further leaderboard improvements.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1840854/69193184-0965bf00-0adb-11ea-8a0d-b20c8c7797e8.png">

Can you please check to see if this is still an issue @viorelaioia?

**Comment by viorelaioia** [comment]
@rileyjshaw , it looks fixed on my end as well.
