### ISSUE TITLE
 "Confirm Goal" button is not greyed-out by default

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/voice-web#2469]
STR:
Prerequisites: Use an account that is new, or an account which doesn't have the "Privacy Policy" accepted

1. Start to set a Goal
2. Reach Step 3 -> please observe the "Confirm Goal" button 

Expected result: The "Confirm Goal" button is greyed-out
Actual result: The "Confirm Goal" button is active even if the user didn't check the Privacy Policy box. 

Note: Here is a screen recording: https://streamable.com/rgcwm

**Comment by rileyjshaw** [comment]
I believe this is intentional. A user can set goals without agreeing to the privacy policy, _if_ they haven't opted into emails. As soon as the newsletter option is selected, we require the user to also check the privacy policy agreement. This matches what I'm seeing in the screen recording, and while testing.

@mbransn can you confirm that this is intended behaviour?

**Comment by mbransn** [comment]
+1 this is indeed as @rileyjshaw has outlined. :) Okay to close.
