### ISSUE TITLE
Home page layout issues between 991px and 1200px

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/voice-web#2592]
Between 991px and 1200px window width there are some minor display errors on the front page.

<img width="1035" alt="Screenshot 2020-02-27 at 00 09 58" src="https://user-images.githubusercontent.com/330324/75396822-5a146180-58ed-11ea-9203-71d17a3ca90e.png">

* 991px and upwards to threshold: No padding left on the main description title 
* Exactly 992px: no profile button visible
* When logged out the login button text gets quite weird

<img width="1017" alt="Screenshot 2020-02-27 at 00 14 33" src="https://user-images.githubusercontent.com/330324/75397035-d3ac4f80-58ed-11ea-8901-9112b8b0bee8.png">

@mbransn what's the desired behavior here? How much padding should the text always have? And I guess the profile button should be visible with 992px as it is with 993px.

**Comment by OsamaAdam98** [comment]
Hey, I'm currently trying my hands at solving this but I came across some design challenges when trying to fix the nav bar. 
When trying to fix how the login button is displayed, various elements around it start to break and overlap

![log-in-sign-up](https://user-images.githubusercontent.com/21957987/75607692-7d642a00-5b02-11ea-8b0b-ba96b68ff915.png)

The easiest possible solution to this would be to remove the "/ sign up" part.

![login-only](https://user-images.githubusercontent.com/21957987/75607702-98369e80-5b02-11ea-82d3-8817f321cdcb.png)

Another solution would be to pump the media query breakpoint to a higher pixel size like 1050px maybe, but this would probably break other things so perhaps not.

I've noticed that the Datasets page has similar padding issues too. I'm tempted to redo the page layout with grid but that'd take some time and probably be redundant since a redesign is already part of the GSoC project.
