### ISSUE TITLE
Implement tooltips for share icons

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2603]
- [ ] As pointed out in #2529, provide a tooltip on hover of the speak portal share icon that states `Share your clip`. Styling should match the re-record icon tooltip.
<img width="1520" alt="Screen Shot 2020-03-03 at 5 09 35 PM" src="https://user-images.githubusercontent.com/18686986/75834752-ce2d8a00-5d71-11ea-8777-ac7a1e70b1c2.png">

---

- [ ] Also apply a tooltip to the share icon on the submission success screen that states `Share Common Voice`. Styling should also match the black, tooltip styling from the re-record icon.
<img width="1455" alt="Screen Shot 2020-03-03 at 4 58 23 PM" src="https://user-images.githubusercontent.com/18686986/75834704-a9d1ad80-5d71-11ea-9d9f-535fa37c8a76.png">

**Comment by mbransn** [comment]
@phirework if you feel this is a good help-wanted or first bug feel free to triage...haha, nvm -- thanks @MichaelKohler

**Comment by Rolikasi** [comment]
Hello, @mbransn, @MichaelKohler. Can I work on this issue?

**Comment by MichaelKohler** [comment]
@Rolikasi sure, go for it! Feel free to ask me anything if you get stuck and I can try to help.

A few notes:
* Make sure to go through the "Import sentences" section in the README, otherwise you won't get to those screens. You can temporarily remove language folders you don't want to import and after the import you can restore them again.
* Note that Common Voice uses a translation framework and these tooltips should be localized as well

**Comment by aryamanpuri** [comment]
@MichaelKohler @Rolikasi  I am sorry, I opened a pr for this issue, before asking whether I should work it or not and honestly I don't read the comment .
Since I have opened the pr for this, can I complete this up?

**Comment by MichaelKohler** [comment]
Oops, I completely missed this.

**Comment by phirework** [comment]
Hey y'all, @aryamanpuri's landed this one already. @Rolikasi, why don't you take a look at #2313?
