### ISSUE TITLE
Ensure correct iOS support messaging is in place for iPad

### ISSUE THREAD

**Issue by mbransn** [mozilla/voice-web#2709]
The current iOS platform support messaging on iPad should direct to Safari (as it does on iPhone). 

**Current messaging:**
![iPad-iOS-Firefox](https://user-images.githubusercontent.com/18686986/80994996-64be0c00-8df2-11ea-8aad-11ebf3d5ff34.jpeg)

**Expected messaging:**
![iPhone-iOS-Firefox](https://user-images.githubusercontent.com/18686986/80995008-6a1b5680-8df2-11ea-861d-d3a46e615f0b.PNG)

This was originally reported on Discourse [here](https://discourse.mozilla.org/t/updates-to-common-voice-for-ios/58909/3) by @Fjoerfoks.

**Comment by mbransn** [comment]
@rileyjshaw tagging you in on this, shout with questions.

**Comment by rileyjshaw** [comment]
@mbransn good catch! The issue here is that iPad's default behaviour is to pretend that it's a Macbook Pro running Mac OS X 10.15 – ugh. I put some time into this today and was able to improve our situation on most browsers, but it's still not perfect.

After commit https://github.com/mozilla/voice-web/commit/38c2e563005ea590bf7fd8bd88669aeb3235b018 lands, we should see the proper mobile error on the following iPad browsers: Chrome, Firefox, Opera Touch, Microsoft Edge, Dolphin<sup>[1](#footnote1)</sup>.

However, we'll still see the default ("desktop") error on more privacy-minded iPad browsers such as Brave and Firefox Focus. If you think this will be confusing for these users, we could change the wording for our error state to be more platform-agnostic<sup>[2](#footnote2)</sup>.

---

<a name="footnote1">1</a>: This isn't a comprehensive list of iOS browsers, but special-casing each one would be a case of diminishing returns. I tested a few less popular browsers with good results.

<a name="footnote2">2</a>: Which brings me to some happier news. In all the hullabaloo around iOS, I'm not sure if I officially announced that it's not _just_ iOS platforms that we support now 😄  I did my best to generalize the solution to all common browsers, which means recording should work in desktop Safari, Edge, etc. Whether on desktop or mobile, not many people will see this error state.

**Comment by mbransn** [comment]
@rileyjshaw agreed it seems not many people will encounter this error state. Do we have an error log in place that will help us track how often this state is triggered and on what platforms/devices? I'd prefer to edit and curate errors based on informed need rather than assumption.

**Comment by rileyjshaw** [comment]
@mbransn we aren't currently logging views of the error state. I could add a tracker, but unfortunately the same problem will exist there; it'll be logged with a desktop user agent. On top of that, Firefox Focus blocks our tracker altogether… our privacy is just too damn good I guess 😂

**Comment by mbransn** [comment]
Ah, got it! Makes sense. In this case I'd prefer we leave as is for now. It's a desktop browser error and would prefer people understand how to contribute via the platform they are most likely to be utilizing. Thank you!.
