### ISSUE TITLE
Language stats are not updated

### ISSUE THREAD

**Issue by nukeador** [mozilla/voice-web#2771]
Language stats on frontpage and /languages are frozen on last week's data.

**Comment by rileyjshaw** [comment]
Thanks for flagging this! It's likely related to the `ER_LOCK_DEADLOCK`s that we've been seeing over the past week or two – either due to high traffic or slow queries. It seems to be updating for me, but I might be missing something. Is there a particular language / configuration you're noticing this for?

**Comment by nukeador** [comment]
For Spanish I see the same data as last week

![imagen](https://user-images.githubusercontent.com/531906/84051913-1a5f1a80-a9b0-11ea-962c-206cde41c1a5.png)

**Comment by rileyjshaw** [comment]
🙏 thank you – will investigate.

**Comment by johanvandyck** [comment]
Hi, I know this is not the subject here, but can you tell me where you find the graph above? I don't see this in my Dutch dashboard.

**Comment by phirework** [comment]
@johanvandyck This graph is on the homepage if you scroll further down. It shows all languages by default, and you should be able to pick Dutch from the dropdown. 

<img width="563" alt="Screen Shot 2020-06-30 at 18 32 20" src="https://user-images.githubusercontent.com/582683/86183490-1aaa8b80-bb00-11ea-8fbb-88c3e79d3d41.png">


The original issue was a database performance problem, where the scripts that refresh leaderboard data were colliding with a big surge of traffic from snippet campaigns. We are planning on revisiting how all of the leaderboard data is handled in H2, and this issue is currently no longer active - @nukeador are you ok if I close this? 

<img width="589" alt="Screen Shot 2020-06-30 at 18 32 36" src="https://user-images.githubusercontent.com/582683/86183496-1ed6a900-bb00-11ea-9114-016fc7f4fff1.png">

**Comment by johanvandyck** [comment]
Hi 

Thanks 

I found it... I alwys landed on the dashboard, not on the homepage.
https://voice.mozilla.org/nl 

For me the update (Dutch) is fine, you can close the ticket, but I'm not
the initiator of the ticket!

---

Met vriendelijke groeten

Johan Van Dyck
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"For every complex problem there is an answer that is simple, short and 
wrong."
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  

                               \\\I///      
                              \\ -- //   
                              (  @ @  )     
----------------------------oOOo-(_)-oOOo-----------------------------------
Johan Van Dyck
Mail: johan@vandyckjohan.be
                            .oooO                                  
 --------------------------- (    )-- Oooo. -------------
                              \  (     (    )
                               \_)     )  /
                                      (_/ 

JZ schreef op 01-07-2020 00:33:

> @johanvandyck [1] This graph is on the homepage if you scroll further down. It shows all languages by default, and you should be able to pick Dutch from the dropdown. 
> 
> [2] 
> 
> The original issue was a database performance problem, where the scripts that refresh leaderboard data were colliding with a big surge of traffic from snippet campaigns. We are planning on revisiting how all of the leaderboard data is handled in H2, and this issue is currently no longer active - @nukeador [3] are you ok if I close this? 
> 
> [4] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [5], or unsubscribe [6].
 

Links:
------
[1] https://github.com/johanvandyck
[2]
https://user-images.githubusercontent.com/582683/86183490-1aaa8b80-bb00-11ea-8fbb-88c3e79d3d41.png
[3] https://github.com/nukeador
[4]
https://user-images.githubusercontent.com/582683/86183496-1ed6a900-bb00-11ea-9114-016fc7f4fff1.png
[5]
https://github.com/mozilla/voice-web/issues/2771#issuecomment-652080942
[6]
