### ISSUE TITLE
Counters (statistics) are not correct

### ISSUE THREAD

**Issue by Sav22999** [mozilla/voice-web#2799]
**Describe the bug**
I've validated about 65 clips and recording about 55 sentences. The counter of ever is incremented (this one:)
![immagine](https://user-images.githubusercontent.com/32335378/86264611-08455600-bbc3-11ea-8ecf-33ea201d17a8.png)

But in "Dashboard" it doesn't work correctly (daily counters):
![immagine](https://user-images.githubusercontent.com/32335378/86264636-14311800-bbc3-11ea-8aa4-d481d2ddcbeb.png)

**To Reproduce**
1. Go to Dashboard
2. See error

**Expected behavior**
It should increment both my counter, personal daily counter and global daily counter

**Screenshots**
Inserted above

**Comment by phirework** [comment]
Hi, thanks for reporting - I think this is a symptom of something that we notice happening when people have the Common Voice website open for a very long time without refreshing or changing the tab, because then when we do a code release, your browser is still using an old version of the frontend to send data to a new version of the backend. Can you confirm if that's something that would apply here? If yes, the fix for it is to hard refresh and try submitting clips again, and the stats should start showing up.

**Comment by Sav22999** [comment]
@phirework it doesn't work

**Comment by phirework** [comment]
Cool, thanks for the feedback, we are investigating.

**Comment by phirework** [comment]
We pushed a fix for this last night, can you verify if your stats are available now?

**Comment by Sav22999** [comment]
@phirework it seems to work now, thanks 😄
