### ISSUE TITLE
Text for initial iOS app and website

### ISSUE THREAD

**Issue by geroter** [mozilla/voice-web#34]
**Home page:**
Build the world's most diverse set of voice data that researchers and others can use for free to create better voice technologies for the Internet. 

[maybe button here?]
Click 'Record' to start donating your voice.

_Your voice donations will be made available for researchers and others to use under a Creative Commons license [https://creativecommons.org/publicdomain/zero/1.0/]. Your name or any other identifying information will not be associated with this voice data._

This project is governed by Mozilla's Privacy Policy [https://mozilla.org/privacy/websites/]

**About page:**
Project Common Voice is brought to you by Mozilla, the proudly non-profit champions of the Internet.

Today's technologies that allow learning from data are freely available for anyone to use, and are resulting a wave of innovation online. However, voice technologies (for example, speech recognition) are not seeing the same innovation because little data is freely available to train machine learning technologies. The data that is available is from a set of speakers with limited diversity of accents and languages.

Our aim with Project Common Voice is to enable "voice donors" to build the world's largest and most diverse set of voice data that is freely available for anyone to use. Our vision is that researchers and others will be able to use this data to increase innovation in voice related technologies. This will help everyone have access to a new wave of voice technologies, and ensure that people aren't locked-in to using services from a small number of Internet giants.

**Comment by mikehenrty** [comment]
This looks good to me! @kdavis-mozilla @mbebenita @andrenatal, thoughts?

I've added it to the site in 26e262b5
https://test.mozvoice.org/

**Comment by kdavis-mozilla** [comment]
@mikehenrty @geroter A few comments on the home page text...

- I guess this is a question for Brain, but should we state the specific CC license instead of "Creative Commons license"? 
- Should the "Donate Now" button be after the end of the text, just to make sure the users know what they're in for before clicking. I know more people will click if it's right after the strong phrase "Interested in helping out? It only takes a minute and doesn't cost you a dime!"
- Could we expand on "researchers and others". For the general public "researchers" are boring and "others" is maybe too vague. It'd be nice if it could be spiced up, something like "Build the world's most diverse voice data set so that startups, researchers, speakers of under represented languages, and that one dreamer in his garage looking to troll the giants can revolutionize the Internet with voice."

**Comment by mikehenrty** [comment]
We've put George's initial text up on the website. @porfitron is going to have a look since he's is also handling copy for the app store. Would be great to have the same text in both!

**Comment by mikehenrty** [comment]
I think we have decent initial text here for now, so let's move the finalization of this bug to Milestone 3, since we should revisit this after we have the initial site design.

**Comment by mikehenrty** [comment]
We have some updated text to integrate into the final design:
https://docs.google.com/document/d/1512EqJhvqsoSmNSCXk-jP48t03MLoykws9BQYA1dCs0/edit

**Comment by mikehenrty** [comment]
Assigning over to @porfitron and @geroter  as they is working on this.

**Comment by mikehenrty** [comment]
Looks like we have a pretty solid idea of the text now on this doc:
https://docs.google.com/spreadsheets/d/1aFG_Mvbj_RH9vS_QvCNDsG8oymONj_xh-Bkc1KEYTyY/edit#gid=0

closing
