### ISSUE TITLE
Nightly - Doesn't seem to like tracking protection mode

### ISSUE THREAD

**Issue by andrenatal** [mozilla/voice-web#369]
(Issue filed on Dees' behalf) Nightly - Doesn't seem to like tracking protection mode - however doesn't work even with it disabled on Nightly. Also seems to false red on Microphone access even though it has been allowed? 

https://www.dropbox.com/s/g6onn5rvoknp274/Screenshot%202017-07-21%2011.37.39.png?dl=0

**Comment by mikehenrty** [comment]
I just test this, and both the microphone recording and listening worked. @andrenatal can you retest this?

> Also seems to false red on Microphone access even though it has been allowed?

That red microphone comes from the browser chrome, not the site, and is by design. Red is the indicator for recording. If you think that's a bug, a good place to report that would be bugzilla for Firefox.

**Comment by mikehenrty** [comment]
I haven't seen this bug for a while, so am going to close. If this resurfaces, let's reopen and investigate.
