### ISSUE TITLE
Pause button on submit page stays paused if submitting while playing

### ISSUE THREAD

**Issue by orschiro** [mozilla/voice-web#419]
Doesn't really affect the usability but thought I am reporting it. 

The last button always shows pause instead of play although it is not playing.

![image](https://user-images.githubusercontent.com/170947/29214453-b9df53ae-7ea7-11e7-9a82-5fb005d23c8d.png)

**Comment by kenrick95** [comment]
Weird, at my side, all are as expected (all three buttons are "play" buttons). What browser & OS are you using? How do you exactly arrive at this situation? Thanks

**Comment by orschiro** [comment]
It happens after I do some recordings in a row.

See this: https://youtu.be/PRBNDeA7RR8

**Comment by kenrick95** [comment]
Okay, now I could reproduce it with this steps:

1. Do 3 recordings to arrive at Submit page
2. Click to play the 3rd entry, but before the recording ends, click submit
3. Do 3 more recordings to again arrive at Submit page
4. Now at the submit page, the 3rd entry will now in the state of "playing" (i.e. showing "Pause" icon)

Probably, this is due to `ListenBox` not being re-mounted at step number 3, hence older state of the component is retained. I think a fix would be to reset `ListenBox`'s state to initial state when its `sentence` props have changed.
