### ISSUE TITLE
Release Access to the Microphone

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#460]
This is possible via the https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop function. 

Also, switching browser tabs, or selecting a different tabs within the app should stop the recording session.

Seeing the recording icon flashing red in the tab, often after several minutes of not touching the app and doing something else, gives me a eerie feeling.

**Comment by Omniscimus** [comment]
Just tried this. Calling the `MediaStreamTrack.stop()` function does release the microphone, but it doesn't remove the flashing microphone icon in Firefox. This icon indicates that you have given the website permission to record audio, not that the website is recording right now. I'll try to make a PR to release the microphone when possible anyway.

**Comment by Omniscimus** [comment]
Hmm, after investigating this, I think releasing the microphone wouldn't help.

The flashing red microphone icon does not go away even when you completely release the microphone (as tested below anyway), because it's not about whether you're recording or having access to the microphone. It just means that you've granted microphone permissions to that website.

Additionally, it involves quite a large overhead. In [audio-web.ts](https://github.com/mozilla/voice-web/blob/255a087405c990bc863809d8bd719fa33d060c1a/web/src/lib/components/pages/record/audio-web.ts):

1. We call `getUserMedia()`, which prompts the user for permission (if the user hasn't already granted this permission) and returns the `MediaStream` resource.
1. We route the `MediaStream` through a bunch of Web Audio API nodes to monitor the volume
1. We create a `MediaRecorder` from the stream to control starting and stopping recordings.

If we wanted to completely free the microphone in a `stop()` call, we would have to do something like `this.recorder.stream.getAudioTracks()[0].stop()`. This stops the original input stream. To record the next sentence, we'd have to request the microphone all over again and go through steps 1, 2 and 3, which is quite a large overhead.

**Comment by mikehenrty** [comment]
Thanks for this careful investigation @Omniscimus .

It sounds like releasing the Microphone is not actually what we want here. Instead, let's just make sure that we stop actively recording when we switch pages, or the page loses focus. The only question would be, does this approach still fix the issue reported in #452?

**Comment by andrenatal** [comment]
Hey guys, could you please test this page: https://people.xiph.org/~jm/demo/rnnoise/donate.html 

Notice that when you click stop the red mike stops pulsing and completely disappears.

**Comment by Gregoor** [comment]
I just looked into this again and noticed that calling `.stop()` on the `MediaStream` is indeed enough to make the recording icon go away. Also when benchmarking it, I didn't see a large overhead introduced by setting up the WebAudio APIs multiple times (though it might also be possible to repeat less of the setup, but let's look at that when we can see/measure a problem).
