### ISSUE TITLE
Create a logo for Common Voice

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#465]
When @m-branson brought up updating the CV wordmark #461, I realized that CV doesn't seem to have its own logo yet either!

The browser tab favicon and the app icon for the iOS app are currently the generic "m" (I guess for "Mozilla").

Would be great to kick off getting a distinct logo/icon to represent the project, @mikehenrty :)

**Comment by m-branson** [comment]
@nevik agreed, the wordmark is one part of a potential branding system for Common Voice. :) An icon would be a nice addition that can be used with/without the wordmark in various applications.

I think @mikehenrty would agree with me when I say that we'd welcome early icon ideas. We aren't quite ready to run a sprint around a specific icon design, but when we are, already having a head start with idea generation would be fantastic! In the interim, please feel free to submit ideas here and we'll be sure to address this in our design roadmap. 👍

**Comment by mmhyamin** [comment]
You can create an issue in [Open Design Repo](https://github.com/mozilla/OpenDesign/issues), if you want community help. :)

**Comment by Djfe** [comment]
togetherness/solidarity for common

microphone/megaphone for recording (maybe with a face next to it)
or mouth and soundwaves for voice

maybe focus that it's **one** voice, the voice of the general public/community. ("allgemeinheit" in German)

a speech bubble containing text is another idea

some images for drawing inspiration
https://logopond.com/logos/newvoices.gif
https://civicrm.org/sites/civicrm.org/files/logo_3e19477f56bb669a076bcc9abddd207a.png
http://lautunddeutlich.info/wp/wp-content/themes/lautunddeutlich/images/lud_logo_.png
https://www.parkett-kessel.de/wp-content/uploads/logo.jpg
https://i0.wp.com/cerasis.com/wp-content/uploads/2013/08/voice-of-the-customer-featured-image.png?fit=596%2C320
http://futurewewant.org/wp-content/uploads/discussion.jpg
http://cdn1.btrstatic.com/pics/hostpics/1b85fcd7-265e-4363-b50f-f2ab040d7459_voicelogo-225px.jpg

maybe also this disc/db icon from the mozilla slides (since it's mainly a massive (verified) database):
https://www.golem.de/1711/131414-149702-i_rc.jpg

We shouldn't use CV in the logo though.
It has too many other meanings by now: Curriculum Vitae, OpenCV, etc.

**Comment by mikehenrty** [comment]
here is an icon exploration from @somratking420:

![image](https://user-images.githubusercontent.com/635365/42564546-52f3c5e2-8501-11e8-9282-bd6853d06cc2.png)

cc: @m-branson for awareness that community members are working on design.

**Comment by angelawyman** [comment]
Will you all be using "Common Voice" as your wordmark globally for other languages? Examining localization and translation concerns). Just thinking about how fluid to make the logo identity so it can be used as part of a system that can accommodate or adapt to further needs .

**Comment by mbransn** [comment]
Hi all, thanks for the input on this! We are going to close this issue as the current wordmark and mars (robot) iconography is the extent to which we are able to invest design resources for branding at the moment.
