### ISSUE TITLE
Stylesheets: Introduce SASS/LESS?

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#470]
From other projects I work on, I'm used to writing stylesheets in higher-level CSS dialects/extensions like SASS/SCSS or LESS.

The most important advantages of these opposed to plain CSS for me are:
* selectors can be nested -> less duplication, more compact, readable and maintainable structure of stylesheets
* variables -> less duplication, more readable code, improved maintainability
* mixins/functions -> as above

The stylesheet for CV already uses CSS variables, so that point doesn't gain much for this project.
However, I still think that nested selectors in particular can improve the structure of the stylesheet(s).

Side note: Since using a higher stylesheet language will need an additional compile-time step, I think we could also consider breaking the stylesheet down into multiple files. In particular, I'd like to keep component-specific style rules next to the respective component(s).

**Comment by mikehenrty** [comment]
I'm really happy with the current CSS compilation process we have (using postcss, cssnext, and cssnano). The idea is that we can write prefix-free, bleeding-edge CSS and then the build takes care of browser compatibility and minification.

Nesting and functions are useful, for sure. But to me I'd rather use standards-based CSS, as this will cast a wider net and promote adoption and evolution of these CSS standards rather than the framework.

As to your side note, I definitely agree it's time to start breaking down the stylesheet into multiple files. It's getting out of hand.

**Comment by nevik** [comment]
A pity for me, but this isn't my personal hobby project. And promoting the adoption of (modern revisions of) open standards is definitely something I can get behind.

I split out the breaking-down of `index.css` into a separate issue :)
