### ISSUE TITLE
Process YT videos to improve Common-voice

### ISSUE THREAD

**Issue by THEPADA** [mozilla/voice-web#532]
Dear Mozilla-Community,

I've contributed to your Voice-Speech relation Database and wondered if you could'nt use Youtube and the Subtitiles from it. I understand, that not all sources are 100% reliable, but if you just use the videos which have real subtitles (and not autocreated one) you should have a lots of training data. Above all should the Videos + Subtitles from Channels like "In a Nutshell" (https://www.youtube.com/user/Kurzgesagt) or "LastWeekTonight" (https://www.youtube.com/user/LastWeekTonight)  be really great sources. What i want to say with it, is that you could also (if you which to have a 99.9% accouracy) whitelist channels which you trust. The audio is easy to grab because there are lots of open source projects ( e.g. https://wiki.ubuntuusers.de/youtube-dl/) and i think extracting the subtitles should also be doable.

I hope i didn't wasted your time and that i could contribute to your awesome Project; Thank you very much

**Comment by mikehenrty** [comment]
Hi there @THEPADA, thank you for the idea!

Videos (or podcasts) with transcripts are indeed extremely valuable to this project. The problem is that we want to publish all the Common Voice data under a CC-0 license, which I understand is incompatible with the Youtube terms of service (see below).

That said, if you know of a source of transcribed videos which might be in the public domain (or whom we could talk to the copyright holder about rights), please feel free to suggest something for us to look into.

Again, thanks for your time, and your voice!


https://www.youtube.com/static?gl=US&template=terms
4. General Use of the Service—Permissions and Restrictions
