### ISSUE TITLE
Set up SonarQube (static code quality analyzer)

### ISSUE THREAD

**Issue by nevik** [mozilla/voice-web#576]
In order to improve and maintain code quality in the project (in the interest of maintainability and further development), I think we should set up a static code quality analyzer like [SonarQube](https://www.sonarqube.org).

SonarQube can be installed "locally" (i.e. on our own servers) if we want, but they also offer [cloud-hosted instances](https://about.sonarcloud.io), which are free for open source projects.

It would be great if could get this up and running, so we know where the code needs the most improvement!

**Comment by Gregoor** [comment]
I'm all for having a linter on this project. Since we're already using ESLint for prettier and it being the quasi standard in the JS community, I'd tend to go with that. Does SonarQube offer something we couldn't do with ESLint? (or is just too inconvenient with it?)
I did look into setting up some basic sanity ESLint rules for this project before (namely no-unused-vars). Unfortunately there were cases where usage of vars as types were not detected (apparently a known issue).

**Comment by nevik** [comment]
SonarQube is not (just) a linter, it has rules to go much further in terms of code quality analysis.

It can give you warnings when a class has too many static dependencies (e.g. number of imports), hinting at too many responsibilities being put into a single class.

It also does more data flow analysis than the typescript compiler does. So it can tell you if you're if-checking for a case that's already ruled out by previous checks (e.g. one thing i noticed and fixed in #575 today).

**Comment by Gregoor** [comment]
I think no of imports, is something eslint could also do. But data flow analysis would definitely be out of its reach.

**Comment by nevik** [comment]
@Gregoor @mikehenrty since the cloud-hosted version of SonarQube (again: free for OSS project) needs maintainer/admin access to the repo (or possibly the org), you guys would need to take care of this (or kick it off with the right people at the mozilla org).

**Comment by Gregoor** [comment]
I'll close this for now, as I don't see a way forward with the cloud-hosted version (i.e. we wouldn't want to/can't give permission for the whole org).
