### ISSUE TITLE
iOS - Determine if we should unlock orientation

### ISSUE THREAD

**Issue by mbebenita** [mozilla/voice-web#64]
Currently, the orientation is locked. We should determine if this is the behavior we want. Since the web site will be responsive, what is the harm in unlocking the orientation?

**Comment by mikehenrty** [comment]
I don't have a preference.

**Comment by mikehenrty** [comment]
@mbebenita can you try this out, and see what it looks like now? in the simulator, it shows the desktop site, which i think works pretty well. interested to hear your opinion

**Comment by mbebenita** [comment]
I don't actually have the ability to build it locally, @andrenatal what do you think if we create an API on the iOS side that we can use to lock and unlock the orientation. We could experiment with it until the last minute and when we make the decision, we can just update the site.

**Comment by mikehenrty** [comment]
I assume you mean a flag in the iOS code and not API to javascript

**Comment by mbebenita** [comment]
API to iOS, so we can toggle the orientation from JS.

**Comment by andrenatal** [comment]
Yes, we can do it. Let me implement it.

On Jun 8, 2017 7:58 PM, "Michael Bebenita" <notifications@github.com> wrote:

I don't actually have the ability to build it locally, @andrenatal
<https://github.com/andrenatal> what do you think if we create an API on
the iOS side that we can use to lock and unlock the orientation. We could
experiment with it until the last minute and when we make the decision, we
can just update the site.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mozilla/voice-web/issues/64#issuecomment-307282328>,
or mute
the thread

**Comment by andrenatal** [comment]
@mbebenita @mikehenrty Do we still need this? I think as we are going to support iPad, the orientation should be always unlocked.

**Comment by mbebenita** [comment]
If we had an API, we could always change our minds later about locking. If that's problematic, then just go with staying unlocked.

**Comment by andrenatal** [comment]
@mikehenrty @mbebenita Ok, I implemented the API to control the orientation. I can be called like [this](https://github.com/mozilla/voice-web/blob/master/ios/voicebank-ios-wrapper/index-cv.html#L70): 

```
    window.webkit.messageHandlers["scriptHandler"].postMessage('lockportrait');
    window.webkit.messageHandlers["scriptHandler"].postMessage('locklandscape');
    window.webkit.messageHandlers["scriptHandler"].postMessage('unlockall');
```
