### ISSUE TITLE
Suggestion: systematize sentence collection for better scaling to another languages

### ISSUE THREAD

**Issue by vhfmag** [mozilla/voice-web#756]
As far as I could find in a quick search, there are few sources of such sentences right now: some static sources (as noted in #23) and user contributions mostly as pastebin links in this repo issues. And support for languages other than English is on the roadmap, but as there are no sources for those, they should take some time to have a large enough corpus to make speech contribution available in those languages.

Maybe a contribution/validation system, akin to the speech one, could be put on place? I'm afraid it could be vandalized, but I really think that, if that's not the case, it would speed up the corpora growth. Another alternative would be to ask for users to translate English sentences to another languages and validate those translations. Does that sound reasonable?

**Comment by zecakeh** [comment]
I don't think the translation is such a good idea because idioms and proverbs could be poorly translated (like litteral translation instead of using the proper expression). Also it would include another validation process, different than the one already in place which in my opinion would complexify the UX. However there are lots of already existing tools for translation (Pontoon, for example), so maybe integration would be faster.

But I like the idea of proposing sentences and having them validated with the same process as the recordings. If such a system was put in place, it would be interesting to check the diversity of the sentences and suggest words to use to the contributors. To do this it would check if all the words of the dictionary are used a certain amount of times. Lists with the most common words of the dictionary should be easy to find. It would also have to check if the sentence is actually an original one, maybe by showing to the user similar phrases already included in the database.

**Comment by vhfmag** [comment]
Indeed, translation is avoidable added complexity, even though it could provide an initial base corpus.

I really like the idea of measuring and rewarding lexical diversity, as it would correlate with phonetic diversity. There, people in the linguistics or NLP fields could probably indicate better such measures (improvements could be such as relying on the word's specific relative frequency of use in a given language instead of a rigid universal threshold). How could it be used? Maybe a health estimate for the sentence corpus shown in a language's page?

Similar phrases would be a great addition too, but I am not sure of the technical feasibility of that beyond simple measures like the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) (I'm not an expert, though, and there could be better and vocabulary-aware alternatives).

About Pontoon, if there are sentences in the English corpus present inside any of Mozilla's products' localization data, maybe their equivalents in other languages could be automatically imported into their corpora?

**Comment by mikehenrty** [comment]
Hi both, thanks for the suggestion. I think this is a great idea!

We are currently working on a process to allow Common Voice users to add new languages to the collection process. As part of that, we need to design a system for collecting corpora in the various languages large enough to start the collection process. This will be a big part of our work in 2018.

On the note of Pontoon, the data in their (from my understanding) uses an attribution license, which from my understanding is not compatible with CC-0 (the Common Voice license).

That said, we will definitely be leveraging Pontoon (and fluent.js) to help with the translation of the website content as we add new languages.

**Comment by Gregoor** [comment]
https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530
