### ISSUE TITLE
[Travis] PR builds perma-failing

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#824]

**Comment by bhavyaagg** [comment]
Hello, Can i try to solve this issue if no one is currently doing this?

**Comment by Gregoor** [comment]
Hey @bhavyaagg, thanks we'd be happy to get ideas around this. Here's our current situation:
One test keeps failing in PRs because Travis doesn't supply AWS credentials when running tests for PRs (which is a reasonable thing to do, security-wise). I pushed a "quick-fix" a few hours ago which just skips the test that rely on AWS S3 when no credentials are given.
The most ideal long-term solution would be to be able to have the local filesystem as an alternative to S3, when no credentials are given. That way we could still run the tests that rely on S3 (/file system) interaction in the PRs.
So if you want to take a stab at implementing a filesystem-alternative to the S3 calls, we'd be happy to facilitate you with getting that in. Other ideas are also welcome!

**Comment by bhavyaagg** [comment]
That would be great. One other thing we might be able to do is to maybe use a test bucket for which we provide the hardcoded keys. But yeah file system approach would be better. Would love to try to solve that.

**Comment by Gregoor** [comment]
That's an interesting idea and in comparison super easy to implement! Wdyt @mikehenrty?

**Comment by bhavyaagg** [comment]
@Gregoor 
I just checked upon Travis builds, one other thing that we can do is,
Add the S3 bucket keys as environment variables in the Travis config using their website and not adding them in the travis.yml so that they are not exposed to public.
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by Gregoor** [comment]
@bhavyaagg that's actually how we do it atm, but when added through the environment variables, it's not used in the PRs. If they were used in the PR they'd practically be public, as some jokster could create a PR that simply reads out env vars and sends them to him.

**Comment by bhavyaagg** [comment]
@Gregoor Yeah that is true. Sorry missed out on that point.

**Comment by bhavyaagg** [comment]
Any update @Gregoor ?

**Comment by mikehenrty** [comment]
hi @bhavyaagg and @Gregoor,

unfortunately, we don't want to expose our test s3 bucket credentials in the repo, as it could end up costing us a log of money if some joker gets a hold of those.

I'm going to close this bug for now, as the [quick fix](https://github.com/mozilla/voice-web/commit/973fde9a1445ac9b44a032b1c49c48573b1989f8) @Gregoor mentioned above seems to address this issue for now.

@bhavyaagg if you are interested in implementing the FS option, let's use #811 to track that work. Thanks for you help!

Fixed in 973fde9a1445ac9b44a032b1c49c48573b1989f8
