### ISSUE TITLE
[Listen] Fetching 2nd sentence take 10s+

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#826]
We can listen to the first audio clip without delay. But after clicking "Yes/No", it takes a long time before we can play the second clip. Long enough that most users will probably give up.

**Comment by mikehenrty** [comment]
Oddly, I'm only seeing this in Firefox (60.0a1). Chrome it loads super fast, and on iPhone it works fine.

**Comment by syilmaz** [comment]
Hi @mikehenrty 

Voting with chrome triggers a 500 error, which is why it seems like it's faster, but it's actually not working:

![afbeelding](https://user-images.githubusercontent.com/250755/35735242-43bc4072-0824-11e8-8b22-60d303f5315c.png)

See HAR ([voice.mozilla.org.har.txt](https://github.com/mozilla/voice-web/files/1689488/voice.mozilla.org.har.txt))

On firefox on the other end the error is 504 Gateway timeout:

![afbeelding](https://user-images.githubusercontent.com/250755/35735263-5c941228-0824-11e8-9e21-4f921f2a071f.png)

**Comment by mikehenrty** [comment]
thanks for all your help on this project @syilmaz!

With this information, it's possible this bug is the same as #831.

The trouble is, we are having some problems with our infrastructure right now so deploying is delayed. @Gregoor has been working on this data and we hope to have a bunch of these things fixed shortly.

Again, thanks!
