### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/voice-web#849]
I would add .editorconfig so the code will be formatted the same in every editor that respects editorconfig. What do you think @Gregoor?

**Comment by mikehenrty** [comment]
Yes please @MekliCZ !

**Comment by Gregoor** [comment]
Interesting idea, but is there something it covers that ESLint doesn't yet (or can't)? I always thought they overlapped in their goals.

**Comment by MekliCZ** [comment]
It's both covered by ESLint and EditorConfig. But I don't know any editor that would respect ESLint settings by default, they usually need plugin and additional configuration. EditorConfig is supported out of the box in VS Code, WebStorm and even GitHub web editor.

**Comment by Gregoor** [comment]
WebStorm/IntelliJ recently learned doing that, looks like for VSCode one still needs a plugin. The reason I'm hesitant to move on this, is because of the overlap in functionality. Could we disable editorconfig for JS files, or maybe configure ESLint to override its own rules with the editorconfig?
I find the CSS bit indeed interesting, though I'm also interested in investigating stylelint for it.

**Comment by MekliCZ** [comment]
Well, I'm editing voice-web in WebStorm and it doesn't really respect ESLint in indentation. It uses editor settings instead.

Sorry for the misunderstanding with VS Code, I wanted to write only VS.

**Comment by Gregoor** [comment]
@MekliCZ afaik when I opened the ESLint file, this popped up:
![ESLint file in WebStorm](https://d3nmt5vlzunoa1.cloudfront.net/webstorm/files/2017/06/import-eslint.png)

**Comment by MekliCZ** [comment]
I have this enabled, but still, it uses editor settings

**Comment by Gregoor** [comment]
Maybe what we should do is just run `yarn pretty` before every commit (as a hook). No editor's code style will be able to replicate what prettier does (afaik), so auto-format is useless anyway. Locally I just have a File Watcher hook that always runs pretty on any file I save.

Somewhat related: there's still some tediousness in our build process due to eslint, style issues shouldn't stop the build, those could be highlighted when trying to commit instead.

**Comment by mikehenrty** [comment]
EditorConfig and Eslint do have overlapping definitions, but they accomplish different things. ESLint is for enforcing *javascript* code style checked into the repo, and EditorConfig is for explicitly telling editors how to *auto-format* documents (not just code) while editing. Yes, for voice-web, we can use ESLint to achieve the same features for our javascript files (although it sounds like @MekliCZ was having problems in VS?). But in any case, I see two advantages to having both EditorConfig and ESLint:

1. Editorconfig is explicit for editor auto-formatting, and as @MekliCZ said many editors will do the right thing out of the box (I'm thinking about new contributors here). For my VIM use case, I _could_ use syntastic with an eslint plugin to achieve this, but it is clunky and slow compared to just using editorconfig which just sets a few attributes when I open a file.
1. It's has a small set of features, people can easily scan the config file and understand our important style choices, while eslint config files can be harder to quickly parse for a human (like ours for example).

In one of my recent large projects, [Firefox OS](https://github.com/mozilla-b2g/gaia/), we had both. Indeed both the [ESLint](https://github.com/eslint/eslint/blob/master/.editorconfig) and [EditorConfig](https://github.com/editorconfig/editorconfig-core-js) projects themselves have both. To me, this feels like an established best practice.

I also tried googling for a blog post or something that talks about the tradeoffs, but all I could find was [this stackoverflow thread](https://stackoverflow.com/questions/48363647/editorconfig-vs-eslint-vs-prettier-is-it-worthwhile-to-use-them-all).

If the worry that these two definitions are getting out of sync, there are also tools that generate .editorconfig from .eslint rules, which we could verify in the build/commit process.

**Comment by Gregoor** [comment]
> we can use ESLint to achieve the same features for our javascript files 
And critically also "more". My point is that it has to go through ESLint anyway, otherwise it currently wouldn't run.

I have yet to see that does auto-formatting consistent with what prettier expects (without just using prettier). To be more precise, yes auto-formatting works for spaces/tabs, parentheses location etc., but afaik not code wrapping (breaking long lines). And even if, that's outside of what editorconfig is trying to accomplish anyway (afaik line length is not an option).

So as I see it, it doesn't buy us much for JS (unless I'm wrong about the above) but adds extra config burden. Anyway if y'all are for it and you're sure it helps you (& others) with development, let's go ahead and get it in.

**Comment by Gregoor** [comment]
:+1: works for me
