### ISSUE TITLE
Support for place names, person names and point of interests

### ISSUE THREAD

**Issue by danielsjf** [mozilla/voice-web#889]
So far, most of the corpora are focused on sentences to get a hang of the actual language. However, many interactions also use names. Should these also be included in the corpora? I assume they are currently indirectly in a subset of the sentences.

There might be some confusing spellings in these location names. For instance, the British place Reading is pronounced as /ˈrɛdɪŋ/, not the same as reading from to read. If these are recorded as separate phonemes, they might cause confusion.

In actual person names, these confusions might go even further. Here it could be nice to also include the most popular names for each year (say top 1000). There are plenty of names [here](http://babynames.net), sorted by top names per decade and ethnicity.

**Comment by JRMeyer** [comment]
@danielsjf --- This is a good point to bring up. For proper nouns such as place names and people names, while their pronunciation is important, for Common Voice, eliciting them will likely cause more harm than good.

Pproper nouns will often be abbreviated as in people's titles (e.g. "Ms. Jones" instead of Miss Jones), locations (e.g. "UAE" instead of United Arab Emirates), or middle / second names (e.g. "J.R.R. Tolkien" instead of Jolkien Rolkien Rolkien Tolkien :wink: ). Joking aside, proper names bring issues along with them that we will have to clean up afterwards, and scaling this to every language in Common Voice is very problematic.

Furthermore, the best place to add proper nouns to ensure their recognition is not in the **audio corpus** from which you train the text-to-speech engine (e.g. DeepSpeech, Kaldi). The best place to put proper nouns is in the **text corpus** from which we train the language model used at decoding time (e.g. kenlm, IRSLTM).

For these reasons, we do not believe that eliciting proper nouns is a good idea for Common Voice.
