### ISSUE TITLE
Staging Server: we need a way to alert people when they are on Staging Common Voice

### ISSUE THREAD

**Issue by mikehenrty** [mozilla/voice-web#923]
Since we have started to post links to the [staging site in](https://voice.allizom.org/) in public places like slack, discourse, and github, I am noticing people are contributing their voice on there. It's easy for people to accidentally post to the wrong place. Let's add a visual call out on the listen and record widget to let people know this is a staging only place.

**Comment by Gregoor** [comment]
[I think I overdid it 🙈 ](https://voice.allizom.org)

**Comment by flyingpimonster** [comment]
@Gregoor Possibly :)

People won't see it if the page is scrolled down, though, so if they switch tabs, they might forget. Plus, the marquee scrolls over the header, which could be annoying. You could solve both these problems by moving the `<marquee>` to the top of the `<body>` and styling it with `position: sticky` instead of `position: absolute`.

Also, the inline scripts are blocked by the Content Security Policy.

**Comment by Gregoor** [comment]
Thanks for the feedback! I think it looks good now. RIP `<marquee>` tho 😢
