### ISSUE TITLE
Edit Profile button reloads page and thereby deletes existing recordings

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#928]
Pressing "Edit profile" while re-recording a phrase deletes all 3 recordings, because the cancel recording button doesn't work
also there is no string displayed on the recording page, if you return from the profile
if you record something and press the backwards button on the next string, it does nothing
if you continue, it will display a blank page after speaking the third (in fact second) string

if you press edit profile during a normal recording, it also deletes previous recordings

**Comment by mikehenrty** [comment]
it seems like all these bugs could just be avoided if we hide the "Edit Profile" button when re-recording.

@m-branson is this something we could consider?

**Comment by m-branson** [comment]
>it seems like all these bugs could just be avoided if we hide the "Edit Profile" button when re-recording.

@mikehenrty yes, for re-recording we could remove the `Edit Profile` option. For a standard recording session, the issue will persist though. I've confirmed @Djfe's note below:

>if you press edit profile during a normal recording, it also deletes previous recordings

Currently there is no way for users to engage a profile after they've started recording without losing their clips. A solution is to duplicate the `Create a Profile` action of opening the form inline beneath the recording session. This would allow users to `Edit Profile` without invalidating a recording session.

At this point we should determine whether to place the effort on updating `Edit Profile` functionality now vs. removing from the record flow in anticipation of the upcoming profile and dashboard work.

Thanks again for the flag @Djfe 👍 

cc @Gregoor @flekkowich

**Comment by Gregoor** [comment]
This one's on me. It used to work, but I introduced a regression with the locale stuff. I just pushed a fix, so that the recordings are retained when going to the profile.

Some technical background info on what happened:
Our Layout Component did the store initilization. That component is remounted once the locale changes. As the "Edit Profile" link goes to `/profile` which redirects to the `DEFAULT_LOCALE` (`/en/profile`), the Layout remounts, thus reinitializing the stores. That didn't happen for the nav links, as they correctly link to the current locales routes (`/en/profile`, `/en/data`, etc.).
I fixed this in two different places. Both would've worked fine on their own, but they are both useful changes:
- store initialization in the root store itself, which only happens once
- make the edit profile route aware of the current locale (we should probably just introduce a LocaleLink-Component that handles that)
