### ISSUE TITLE
buttons for closing pop-ups are inconsistent

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#930]
There are two buttons "Return to Languages" and "Return to Common Voice" on the same page (Languages)
They are displayed in the pop-ups of that page.

But one looks like a link and the other one looks like a button (different css)

Also: the strings don't match/it looks inconsistent.
The same goes for: "Exit form" and "Exit"

In german I translated the first string like the second one, so it matches up (simply "Return to Common Voice" in both cases).

I also found it a bit weird to have two buttons: close form and return to common voice, that do the same thing.
This should be changed somehow IMO.

a possible string, that might be better:
"Continue"

String one:
![screenshot](https://i.imgur.com/DwWHR7f.png)

String two:
![screenshot](https://i.imgur.com/Oq18wWZ.png)

**Comment by mikehenrty** [comment]
flagging @m-branson for awareness

**Comment by m-branson** [comment]
Thanks for flagging this @Djfe, much appreciated!

For `Exit` and `Exit Form` we are working to consolidate this into a simple `X` icon which will close any overlay and route back to the origin screen.

For the `Return to ...` buttons, this is an artifact of iterative design process. 😬 Two thoughts:
- Visually: both instances should utilize the latest version of black button UI. @Gregoor apologies here as this is my inconsistency. 
- Functionally: (for the moment**) button routing is correct. This provides a user experience that accommodates different user types: those that are comfortable closing/exiting an overlay vs. those that prefer a button style call to action.
**It is our goal in the very near future to instead route users more effectively for the project; e.g. `Share the Common Voice Project` (provides UI to share socially or via URL) or `Ready to record some clips?` (prompts and routes users to make contributions if their language is available)

Regarding this:
>In german I translated the first string like the second one, so it matches up (simply "Return to Common Voice" in both cases).

In this instance the `Return to Languages` option should be routing to the Languages page, this is why we've used this copy rather than `Return to Common Voice`. If possible it'd be great to keep `Return to Languages` as button copy for the `Get Involved` overlay flow.

cc @mikehenrty @flekkowich

**Comment by Djfe** [comment]
> In this instance the Return to Languages option should be routing to the Languages page, this is why we've used this copy rather than Return to Common Voice. If possible it'd be great to keep Return to Languages as button copy for the Get Involved overlay flow.

I just noticed, that not only is the "Get Involved" overlay flow displayed on the main page atm. (release server only), but the button also says ```Return to Languages```

Just thought, you might wanna know that. :)

**Comment by m-branson** [comment]
>I just noticed, that not only is the "Get Involved" overlay flow displayed on the main page atm. (release server only), but the button also says Return to Languages

@Djfe on my end both staging and production are showing the proper flows for our current iteration:
- `Request a Language` on the homepage and within the banner on Laguages page
- `Get Involved` on the Languages page for each language

Perhaps I'm misunderstanding what you're referencing? A screenshot may help too.

**Comment by Djfe** [comment]
yeah, probably because it only shows up for other languages than English ^^
![screenshot_20180510-215246](https://user-images.githubusercontent.com/5685512/39890932-98a88d88-549c-11e8-8535-cddd86a8c380.png)
change it to German and click on "mitmachen" ;)

**Comment by m-branson** [comment]
Ah yes, this explains very well why I didn't know it was incorrect! Thanks for clarifying and QA'ing @Djfe 👍 

@Gregoor can you look into this and ensure the strings are updated for our next push? (Wondering if this may be left over due to translation freeze prior to our last push?)

**Comment by Gregoor** [comment]
Oh right, when we were building that we were only thinking about opening up from the languages page I guess. I'll see if I can find an existing string which we can show on the home get-involved instead.

**Comment by m-branson** [comment]
@Gregoor I believe this should be `Return to Common Voice`?
