### ISSUE TITLE
language selection - sorting

### ISSUE THREAD

**Issue by Djfe** [mozilla/voice-web#939]
I have a suggestion to sort the languages differently:
First: currently selected
Second: browser's language
Third: English
Then all other languages alphabetically

Advantages:
the select element on mobil is scrolled down, so that the selected entry is on top.
Implementing it this way you'll only have to scroll down and have the most likely language on top. (maybe Russian or Portugese could be on top instead of English, when they are more likely, but the website doesn't support the browsers language natively, but that is just an afterthought)

**Comment by Gregoor** [comment]
I'd argue we don't need to do that, for the following reasons:

Currently selected: The dropdown is now scrolled so that this one should be immediately visible.
Browser Language: When visiting https://voice.allizom.org you'll be redirected to the browser language.
English: I don't think we'd want to give it extra priority over other languages tbh.

**Comment by Djfe** [comment]
ok fine by me, that was just an idea, that was floating around in my head that I wanted to share :)

**Comment by mikehenrty** [comment]
Thanks for the thoughts here @Djfe. I'm inclined to agree with @Gregoor. That said, I would love to see if @m-branson has any thoughts.

**Comment by Gregoor** [comment]
@Djfe hope I didn't come across schroff, it's an idea worth considering!
