### ISSUE TITLE
Languages progress bar: 'total' label needs updating

### ISSUE THREAD

**Issue by m-branson** [mozilla/voice-web#953]
@mikehenrty @Gregoor apologies for not catching sooner...the 'Total' title for the progress bar on our language cards is not clear enough. Meaning, 'total of what?' -- 'Strings Translated' is what I'm assuming at this stage, but we are not communicating that in the UI. Therefore it looks like most 'In Progress' languages should be launching soon (as they're at an ambiguous 100%).

Can we update 'Total' to something more descriptive for launch? When we come back to the language epic for iteration we can further determine how to best use this progress bar -- it was orginally intended to show _overall_ progress for a language, not just one step. As it sits currently these languages are at about step 1 of 5(?) complete, rather than 100%.

<img width="414" alt="screen shot 2018-04-26 at 4 07 51 pm" src="https://user-images.githubusercontent.com/18686986/39336372-005d2236-496c-11e8-9cd7-b21d3644f030.png">

**Comment by mikehenrty** [comment]
How about `Progress`?

**Comment by mikehenrty** [comment]
@m-branson the problem with `Translation` is that we don't already have that word in Pontoon (ironic we don't have that word). This means we would put some last minute burden on our localizers, when we promised our strings would be frozen for launch about 2 weeks ago. Peiying, our l10n community lead, recommends we always give 2 weekends notice before big launches to set expectations.

For context, I just went back to the invision discussion thread we had about this a few months back (I couldn't figure out how to link to it here, but it's on the languages page for the language flow). How about we fix the percentage bar itself rather than the word? If we represent the website translation as 50% of the meter, and then sentence collection as the other 50% of the meter, I think we can keep the `Total` word, thereby keeping our promise of no string changes to our localizers, and giving a more accurate picture of launch progress in this meter. This would be an easy engineering fix, and seems to be more the direction we want to go in the long run anyway.

@m-branson thoughts?

**Comment by m-branson** [comment]
@mikehenrty ah yes, that makes complete sense. Thanks for clarifying that need for string freeze.

100% agree with adjusting the progress bar to accurately reflect the phases. This is an obvious solution that I sadly completely overlooked. Let's implement that change, it is indeed needed for the long run. :)

Thanks for taking the time to review and think through. 👍 

cc @Gregoor
