### ISSUE TITLE
English strings from the Privacy Notice missing in pontoon/tt/common-voice

### ISSUE THREAD

**Issue by IlnarSelimcan** [mozilla/voice-web#998]
On https://voice.allizom.org/tt/privacy, Kazakh translation is shown instead of Tatar.

Apparently the Privacy Notice has been updated and thus Tatar translation got out of date and hence is not shown on the website.

I figured I need to update the translation on https://pontoon.mozilla.org/tt/common-voice/, but when I search for the English phrases from the Privacy Notice, e.g. https://pontoon.mozilla.org/tt/common-voice/all-resources/?search=Technical+data no strings will show up.

What might be the issue here? Probably related to #984 .

**Comment by Gregoor** [comment]
Thanks for reporting that!

We had our privacy & terms in Pontoon a while ago, but then switched to getting it from the [Mozilla Legal Repo](https://github.com/mozilla/legal-docs/tree/master/Common_Voice_Privacy_Notice). It looks like there was a mix-up there. Can you help @peiying2?

**Comment by peiying2** [comment]
@IlnarSelimcan I apologize for this mixup. I looked for the history of this, and I wish we still had the strings in Pontoon (or maybe through checking voice webpart repo in GitHub) where I got the content and created it in the legal doc repo.  The original translation in Pontoon comes from the "tt" team. 

Most importantly, there is no Kazakh locale for CV project in Pontoon, so it is not like I accidentally copied the incorrect language: https://pontoon.mozilla.org/projects/common-voice/. 

The reason you can't find it in Pontoon now is because Legal content should be separate from the rest of the project. Many people don't feel comfortable translating it, resulting higher number of incomplete locales. We then moved the strings to legal repo: https://github.com/mozilla/legal-docs/tree/master/Common_Voice_Privacy_Notice. I copied the strings from what were once in Pontoon. 

https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Terms/tt.md
https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Privacy_Notice/tt.md

Keep in mind, we didn't want to localize the legal locales for all the languages. The reason we did it for tt and others was because each of these communities completed 50%+ of the legal content. We didn't want it to go wasted so we leveraged the content and asked the agency to update and finish the rest.

Let me know if we should disable both or have the agency redeliver for Tartar. I can arrange that.

Thank you,
Peiying

**Comment by ftyers** [comment]
@peiying2 +1 for people not feeling comfortable translating legal notices. It should be possible for people to specify a "fallback language" in this case. E.g. for Tatar/Chuvash probably Russian would make sense. 

if you paid for the Tatar translation, you should certainly ask for them to either translate it again or get your money back. Kazakh is not Tatar :) ... imagine asking for an English translation and getting Dutch!

**Comment by peiying2** [comment]
@ftyers There is no Russian legal doc at the moment. This could change in the future. For the time being, do you prefer to have it taken down? Also, you saw my explanation in my comment, the Kazakh version was leveraged copied from Pontoon, so at some point "tt" at least for legal content, was mixed up there. The agency finished up the rest for this locale and others that were half incomplete.

**Comment by IlnarSelimcan** [comment]
Should I replace Kazakh text in https://github.com/mozilla/legal-docs/blob/master/Common_Voice_Privacy_Notice/tt.md with Tatar translation of the privacy notice and make a pull request?

**Comment by IlnarSelimcan** [comment]
Also, do I understand it correctly that there is no way to restore the Tatar translation of the Common Voice Privacy Notice and the Common Voice Terms which i had completed from Pontoon?

**Comment by peiying2** [comment]
@IlnarSelimcan, no the legal doc content should have not been put in Pontoon with the rest of the web content. It is in the github repo for legal docs. I can work on getting a Russian version done so it can be a fallback language for many languages.

**Comment by peiying2** [comment]
@IlnarSelimcan The mixup is fixed by adding kk.md and removing tt.md in both docs. Additionally, we now have Russian as the fallback language. Thanks for bringing this to our attention.
